import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Beliefs() {
  return (
    <>
      <Head>
        <title>r/mensrights analysis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ul className={styles.topnav}>
          <li className={styles.navli}>
            <Link href="/" className={styles.navLink}>
              r/MensRights Analysis
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/general" className={styles.navLink}>
              General Info
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/rules" className={styles.navLink}>
              Rules
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/language" className={styles.navLink}>
              Language
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/beliefs" className={styles.active}>
              Beliefs
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/rituals" className={styles.navLink}>
              Rituals
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/characters" className={styles.navLink}>
              Characters
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/funExtras" className={styles.navLink}>
              Fun Extra Stuff
            </Link>
          </li>
        </ul>
        <div className={styles.spacing}>
          <h1 className={styles.title}>Beliefs</h1>
        </div>
        <div className={styles.spacing}>
          <div className={styles.card}>
            <h2 className={styles.title}>What does r/MensRights believe in?</h2>
            <p>
              The goals of this subreddit are clear: gender equality. More
              specifically, gender equality for men. That means that all members
              of this subreddit have two main beliefs:
            </p>
            <ol className={styles.lists}>
              <li>
                <p>
                  Men are not as priveledged as other genders in western society
                </p>
              </li>
              <li>
                <p>
                  Work needs to be done so men can become equal to all other
                  genders
                </p>
              </li>
            </ol>
            <p>
              As a result of this mindset, there are many notions, ideas, and
              opinions members of this community share.
            </p>
          </div>
          <div className={styles.spacing}>
            <h2 className={styles.title}>Unified Beliefs</h2>
            <div className={styles.multipleC}>
              <div className={styles.accentcardR2}>
                <h3 className={styles.title}>Men and Women Are Not Equal</h3>
                <hr className={styles.rulesHr} />
                <p className={styles.decorativep2}>
                  Most users in this community believe that women are more
                  valued in society as men. Specifically, they believe women
                  have more freedom since they are expected to be the
                  breadwinner in relationships.
                </p>
              </div>
              <div className={styles.middle}></div>
              <div className={styles.accentcardR2}>
                <h3 className={styles.title}>
                  The Legal System is Unfair Towards Men
                </h3>
                <hr className={styles.rulesHr} />
                <p className={styles.decorativep2}>
                  Many believe that men are punished more harshly by the legal
                  system than women. In their opinion, it is most apparent when
                  dealing with divorce and custody cases. Many men believe women
                  take advantage of child support and get unfair advantages in
                  custody battles
                </p>
              </div>
            </div>
            <div className={styles.multipleC}>
              <div className={styles.accentcardR2}>
                <h3 className={styles.title}>Fear of Being Falsely Accused</h3>
                <hr className={styles.rulesHr} />
                <p className={styles.decorativep2}>
                  While the &apos;False Accusation&apos; flair is only meant to
                  be used to proven false accusations, many men use it to
                  express their fear of being accused of sexual assault. A
                  considerable amount of men believe it could happen to them
                  even if they&apos;ve done nothing wrong.
                </p>
              </div>
              <div className={styles.middle}></div>
              <div className={styles.accentcardR2}>
                <h3 className={styles.title}>
                  The Men&apos;s Rights Movement is not Anti-Feminism
                </h3>
                <hr className={styles.rulesHr} />
                <p className={styles.decorativep2}>
                  Most users wish to make it clear that the movement does not
                  exist to negate feminism. They may critique the movement but
                  they are not anti-woman. Users are pretty good at calling out
                  the misogynistic opinions of other members.
                </p>
                <p className={styles.decorativep2}>
                  They also state that while feminism is supposed to support all
                  genders, they do not think it is helpful to the men&apos;s
                  rights movement
                </p>
              </div>
            </div>
          </div>
          <div className={styles.spacing}>
            <div className={styles.personalCard}>
              <h4 className={styles.title}>Personal Note:</h4>
              <hr className={styles.prLine} />
              <br />
              <p>
                There are a wide range of other opinions in this community but
                these were the opinions I saw the most during my research. I do
                not believe it&apos;s fair to judge a community based on their
                extremists, which is why there are very few unified beliefs.
              </p>
              <br />
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
