import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Characters() {
  return (
    <>
      <Head>
        <title>r/mensrights analysis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ul className={styles.topnav}>
          <li className={styles.navli}>
            <Link href="/" className={styles.navLink}>
              r/MensRights Analysis
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/general" className={styles.navLink}>
              General Info
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/rules" className={styles.navLink}>
              Rules
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/language" className={styles.navLink}>
              Language
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/beliefs" className={styles.navLink}>
              Beliefs
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/rituals" className={styles.navLink}>
              Rituals
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/characters" className={styles.active}>
              Characters
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/funExtras" className={styles.navLink}>
              Fun Extra Stuff
            </Link>
          </li>
        </ul>
        <div className={styles.spacing}>
          <h1 className={styles.title}>Characters</h1>
        </div>
        <div className={styles.spacing}>
          <h2 className={styles.title_center}>
            The Characters of r/MensRights
          </h2>
          <div className={styles.spacing}>
            <div className={styles.card}>
              <h2 className={styles.title}>The Jokester</h2>
              <p>
                These users exclusively post memes and make jokes in the comment
                sections of posts. Some jokes are satirical while others are
                malicious; however, a majority of jokers are light-hearted.
              </p>

              <p>
                Posts made by these users are usually found under the{" "}
                <strong>Humor</strong> flair and comments made by them tend to
                be very popular (highly upvoted).
              </p>
            </div>
          </div>
          <div className={styles.spacing}>
            <div className={styles.card}>
              <h2 className={styles.title}>The Discusser</h2>
              <p>
                These users submit posts to discuss topics revolving around
                Men&apos;s Rights in a serious manner. They tackle topics
                discussed in the Reference Book of Men&apos;s Rights either
                through posts or insightful comments.
              </p>

              <p>
                These users tend to post articles about more hard hitting topics
                like social issues, false accusations, legal discrimination,
                etc.
              </p>
            </div>
          </div>
          <div className={styles.spacing}>
            <div className={styles.card}>
              <h2 className={styles.title}>The Ally</h2>
              <p>
                This is mostly women in the group (overwhelmingly mothers) who
                have joined to learn about the movement and help how they can.
                They tend to ask lots of questions about certain issues from the
                male perspective and ask for advice on how to approach certain
                topics with their husbands and/or sons.
              </p>

              <p>
                Posts made by these users are usually found under the{" "}
                <strong>General</strong> flair and users tend to be kind to them
                in the comments. The community seems to appreciate women trying
                to understand their point of view.
              </p>
            </div>
          </div>
          <div className={styles.spacing}>
            <div className={styles.card}>
              <h2 className={styles.title}>The Hater</h2>
              <p>
                These users can be labeled the trolls of this subreddit. They
                rarely post but leave a slew of negative comments about women,
                the government, other users in the sub, etc.
              </p>

              <p>
                These users typically get banned if they cross a line set by the
                moderators and usually are only seen commenting under a few
                posts. None are extremely active.
              </p>
            </div>
          </div>
          <div className={styles.spacing}>
            <div className={styles.card}>
              <h2 className={styles.title}>The Silent</h2>
              <p>
                There are way more members than there are active members of this
                subreddit, so many read and absorb the content posted without
                doing so themselves.
              </p>
              <p>
                Their unwillingness to participate could stem from shyness, fear
                of being discovered, or the desire to just spectate the
                discussions going on
              </p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
