import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export default function FunExtras() {
  return (
    <>
      <Head>
        <title>r/mensrights analysis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ul className={styles.topnav}>
          <li className={styles.navli}>
            <Link href="/" className={styles.navLink}>
              r/MensRights Analysis
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/general" className={styles.navLink}>
              General Info
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/rules" className={styles.navLink}>
              Rules
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/language" className={styles.navLink}>
              Language
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/beliefs" className={styles.navLink}>
              Beliefs
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/rituals" className={styles.navLink}>
              Rituals
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/characters" className={styles.navLink}>
              Characters
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/funExtras" className={styles.active}>
              Fun Extra Stuff
            </Link>
          </li>
        </ul>
        <div className={styles.spacing}>
          <h1 className={styles.title}>Fun Extra Stuff</h1>
        </div>
        <div className={styles.spacing}>
          <div className={styles.card}>
            <h2 className={styles.title}>Silly Goofy CS Major</h2>
            <p>
              I am a CS major and couldn&apos;t do a project on a subreddit
              without doing some fun text analysis stuff using R. Here&apos;s
              the stuff I found the most interesting.
            </p>
          </div>
        </div>
        <div className={styles.spacing}>
          <div className={styles.accentcardR3}>
            <h2 className={styles.title}>What is a Sentiment Analysis?</h2>
            <hr className={styles.rulesHr} />
            <p>
              the process of computationally identifying and categorizing
              opinions expressed in a piece of text, especially in order to
              determine whether the writer&apos;s attitude towards a particular
              topic, product, etc. is positive, negative, or neutral.
            </p>
          </div>
        </div>
        <div className={styles.spacing}>
          <div className={styles.imgdiv}>
            <Image
              src="/overall.png"
              width={1300}
              height={1000}
              alt="Overall Sentiment Score"
            />
          </div>
        </div>
        <div className={styles.spacing}>
          <div className={styles.card}>
            <h2 className={styles.title}>
              r/MensRights: Overall Sentiment Score
            </h2>
            <p>
              The graph above displays the overall sentiment of the all-time top
              100 posts of the subreddit r/MensRights.
            </p>
            <p>
              The greatest sentiment shared between it&apos;s users is
              positivity followed closely by negativity. That relationship makes
              a lot off sense considering the strong sense of community yet
              heated debates going on in this subreddit. While the vibes are
              mostly positive, the debates get very heated depending on the
              topic being discussed.
            </p>
            <p>
              Trust is also high on graph, implying that users feel safe in this
              community. This is definitely something I&apos;ve observed over
              the past few weeks. Men feel more inclined to post their &quot;Hot
              Takes&quot; on this page because this community is more likely to
              sympathize with them.
            </p>

            <p>
              It&apos;s also important to note how fear and anger stand out in
              this graph as well. Based on my observation, the fear factor
              likely comes from men who are scared being falsely accused for
              assault. The anger likely stems from those heated debates I
              mentioned earlier.
            </p>
          </div>
        </div>
        <div className={styles.spacing}>
          <div className={styles.imgdiv}>
            <Image
              src="/topwords.png"
              width={1300}
              height={1000}
              alt="Top Words Count"
            />
          </div>
        </div>
        <div className={styles.spacing}>
          <div className={styles.card}>
            <h2 className={styles.title}>r/MensRights: Title Top Words</h2>
            <p>
              The graph above displays the top words used in the titles of the
              all-time top 100 posts of the subreddit r/MensRights.
            </p>
            <p>
              <i>Note</i>: I omitted filler words such as &apos;a&apos;,
              &apos;the&apos;, etc. to maximize the depth of our findings.
            </p>
            <p>
              To no surprise, &quot;men&quot; is the most use word in titles in
              this subreddit. The words male, man, boy and father also make an
              appearance on the list. Considering the page is supposed to
              discuss men&apos;s rights issues this checks out.
            </p>

            <p>
              Women, woman, female, and feminist also made the top words used in
              titles. I find this interesting because based on the amount of
              times those words were used in titles. Given that titles hint on
              the content of the post, it leads me to believe this subreddit
              discussing women quite a bit.
            </p>

            <p>
              It is also worth noting that &quot;accused&quot; and
              &quot;rape&quot; made this list. Out of context that sounds wild,
              but it&apos;s likely due to the shared fear this community has of
              being falsely being accused of sexual assault.
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
