import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export default function Rules() {
  return (
    <>
      <Head>
        <title>r/mensrights analysis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <ul className={styles.topnav}>
          <li className={styles.navli}>
            <Link href="/" className={styles.navLink}>
              r/MensRights Analysis
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/general" className={styles.navLink}>
              General Info
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/rules" className={styles.active}>
              Rules
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/language" className={styles.navLink}>
              Language
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/beliefs" className={styles.navLink}>
              Beliefs
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/rituals" className={styles.navLink}>
              Rituals
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/characters" className={styles.navLink}>
              Characters
            </Link>
          </li>
          <li className={styles.navli}>
            <Link href="/funExtras" className={styles.navLink}>
              Fun Extra Stuff
            </Link>
          </li>
        </ul>
        <div className={styles.spacing}>
          <h1 className={styles.title}>Rules</h1>
        </div>
        <div className={styles.spacing}>
          <div className={styles.card}>
            <h2 className={styles.title}>General</h2>
            <p>
              r/MensRights is required to follow reddit&apos;s universal code of
              conduct which restricts bully/hate speech, protects privacy,
              prevents manipulation etc.
            </p>
            <p>
              Subreddits are also given the option to outline their own
              community guidelines. The moderators of r/MensRights enforce 14
              subreddit specific rules.
            </p>
          </div>
        </div>
        <h2 className={styles.title}>r/MensRights Specific Rules</h2>
        <div className={styles.spacing}>
          <div className={styles.multipleC}>
            <div className={styles.accentcardR2}>
              <h3 className={styles.title_center}>
                All Posts Must Be Related to Men&apos;s Rights
              </h3>
              <hr className={styles.rulesHr} />
              <br />
              <p className={styles.decorativep2}>
                Submissions that fall under the category of men&apos;s rights
                include:
              </p>
              <ul className={styles.lists}>
                <li>
                  <p>Discrimination against men</p>
                </li>
                <li>
                  <p>Issues that disproportionally affect men</p>
                </li>
                <li>
                  <p>
                    Problems that prevent men&apos;s issues from being addressed
                  </p>
                </li>
              </ul>
              <p className={styles.decorativep2}>
                Each post much make clear the relationship between its content
                and the fight for men&apos;s rights.
              </p>
            </div>
            <div className={styles.middle}></div>
            <div className={styles.accentcardR2}>
              <h3 className={styles.title_center}>
                Post Must Provide Value to the Sub. No Fake News
              </h3>
              <hr className={styles.rulesHr} />
              <br />
              <p className={styles.decorativep2}>
                Users should not post unlabelled satirical content, memes, low
                effort discussions, or fake news.
              </p>
              <p className={styles.decorativep2}>
                If the post does contain satire, it must include{" "}
                <strong>[Satire]</strong> in its title.
              </p>
              <p className={styles.decorativep2}>
                The moderators warn against low-effort images and text posts
                since they want serious discussions to take place in the
                subreddit.
              </p>
            </div>
          </div>
        </div>
        <div className={styles.spacing2}>
          <div className={styles.multipleC}>
            <div className={styles.accentcardW2}>
              <h3 className={styles.title_center}>
                Meta Discussions should be posted in r/MensRightsMeta
              </h3>
              <hr className={styles.rulesHr2} />
              <br />
              <p className={styles.decorativep3}>
                If a user wishes to discuss meta issues in this subreddit they
                should cross-post from the{" "}
                <Link
                  href="https://www.reddit.com/r/MensRightsMeta/"
                  className={styles.intextLink}
                  target="_blank"
                >
                  r/MensRightsMeta
                </Link>{" "}
                page; otherwise, they should limit those discussions to that
                subreddit.
              </p>
              <p className={styles.decorativep3}>
                All cross-posts must include the <strong>[META]</strong> tag
              </p>
            </div>
            <div className={styles.middle}></div>
            <div className={styles.accentcardW2}>
              <h3 className={styles.title_center}>
                Cross-Linking and Cross-Posting are Restricted
              </h3>
              <hr className={styles.rulesHr2} />
              <br />
              <p className={styles.decorativep3}>
                Cross-Linking and Cross-Posting refer to posting content and
                links from other subreddits on this one.
              </p>
              <p className={styles.decorativep3}>
                Cross-linking/posting from subreddits with fewer than 30,000
                members within the first 24 hours is banned.
                Cross-linking/posting can only be done via NP links or
                screenshots (replace www with np at the front of the link).
              </p>
              <p className={styles.decorativep3}>
                Cross-linking from the subreddits{" "}
                <Link
                  href="https://www.reddit.com/r/againstmensrights/"
                  className={styles.intextLink}
                  target="_blank"
                >
                  r/AgainstMensRights
                </Link>{" "}
                and &quot;r/TheFairerSex&quot; is banned.
              </p>
            </div>
          </div>
        </div>
        <div className={styles.spacing}>
          <div className={styles.personalCard}>
            <h4 className={styles.title}>Personal Note:</h4>
            <hr className={styles.prLine} />
            <br />
            <p>
              The existence of{" "}
              <Link
                href="https://www.reddit.com/r/againstmensrights/"
                className={styles.intextLink2}
                target="_blank"
              >
                r/AgainstMensRights
              </Link>{" "}
              is really interesting. Its purpose is to call out hypocrisy and
              misogyny in r/mensrights and is in the top 5% of subreddits in
              terms of people who interact with it. Considering the fact that
              r/mensrights advertises itself as a place to openly discuss
              men&apos;s rights issues, it is unusual that they would silence
              the opposite side of the conversation.
            </p>
            <br />
            <p>
              r/TheFairerSex was banned from reddit (I am unsure exactly when it
              was banned) for violating community guidelines. The reason cited
              was that they were promoting hate and hate speech.{" "}
            </p>
            <br />
          </div>
        </div>
        <div className={styles.spacing2}>
          <div className={styles.multipleC}>
            <div className={styles.accentcardR2}>
              <h3 className={styles.title_center}>No Personal Information</h3>
              <hr className={styles.rulesHr} />
              <br />
              <p className={styles.decorativep2}>
                All personal information posted will be removed for the safety
                of the users.
              </p>
              <p className={styles.decorativep2}>
                The moderators also require that posts from social media have
                names/usernames blanked out to protect user privacy. They also
                do not tolerate users attempting the identify anonymous users.
              </p>
            </div>
            <div className={styles.middle}></div>
            <div className={styles.accentcardR2}>
              <h3 className={styles.title_center}>
                All NSFW Content Needs to be Labelled
              </h3>
              <hr className={styles.rulesHr} />
              <br />
              <p className={styles.decorativep2}>
                NSFW is short for &quot;Not Safe For Work&quot;. It mostly
                refers to discussions about sex and/or sexuality.
              </p>
              <p className={styles.decorativep2}>
                The moderators feel it is important for users to label that
                content so no one is exposed to these discussions if they do not
                wish to be.
              </p>
            </div>
          </div>
        </div>
        <div className={styles.spacing2}>
          <div className={styles.multipleC}>
            <div className={styles.accentcardW2}>
              <h3 className={styles.title_center}>
                No Reposts, Spam, Ads, Fakes, or Subreddit Bans
              </h3>
              <hr className={styles.rulesHr2} />
              <br />
              <p className={styles.decorativep3}>Users Cannot:</p>
              <ul className={styles.lists}>
                <li>
                  <p>advertise products, services, or your own subreddit</p>
                </li>
                <li>
                  <p>make multiple, identical posts</p>
                </li>
                <li>
                  <p>post about being banned from other subreddits</p>
                </li>
                <li>
                  <p>repost recently posted content</p>
                </li>
                <li>
                  <p>post fake screenshots</p>
                </li>
              </ul>
            </div>
            <div className={styles.middle}></div>
            <div className={styles.accentcardW2}>
              <h3 className={styles.title_center}>
                No Advocating for Illegal Actions
              </h3>
              <hr className={styles.rulesHr2} />
              <br />
              <p className={styles.decorativep3}>Restricted Topics Include:</p>
              <ul className={styles.lists}>
                <li>
                  <p>
                    the use of child pornography (with the specification “even
                    to curb pedophilia”){" "}
                  </p>
                </li>
                <li>
                  <p>
                    unlawful violence and/or threats (with the exception of
                    self-defense)
                  </p>
                </li>
              </ul>
              <p className={styles.decorativep3}>
                A Note included with this rule:
              </p>
              <blockquote className={styles.quoteS}>
                &quot;Discussion of appropriate punishment for illegal
                activities, about self-produced pornography (i.e. sexting),
                about whether cartoon images are child porn, and about mid-teen
                level &quot;consensual&quot; relationships are allowed.&quot;
              </blockquote>
            </div>
          </div>
        </div>
        <div className={styles.spacing}>
          <div className={styles.personalCard}>
            <h4 className={styles.title}>Personal Note:</h4>
            <hr className={styles.prLine} />
            <br />
            <p>
              I was shocked to see that under their &quot;No Illegal
              Actions&quot; rule the first action prohibited had to do with
              child pornography. The specification regarding curbing pedophilia
              implies that is was previously discussed often enough that they
              had to ban it. From my perspective, that is a terrifying thought.
              It negatively colors my view of the subreddit and the type of
              people it attracts but I do appreciate that the moderators put a
              stop to it.
            </p>
            <br />
          </div>
        </div>
        <div className={styles.spacing2}>
          <div className={styles.multipleC}>
            <div className={styles.accentcardR2}>
              <h3 className={styles.title_center}>
                No Harassment/Personal Attacks
              </h3>
              <hr className={styles.rulesHr} />
              <br />
              <p className={styles.decorativep2}>
                Users are not allowed to personally attack other users during
                discourse. Moderators have a right to censor users if they are
                prone to harassing others. Users are also not allowed to makes
                posts criticizing a specific user.
              </p>
            </div>
            <div className={styles.middle}></div>
            <div className={styles.accentcardR2}>
              <h3 className={styles.title_center}>
                Racism and Other Hate Speech Restrictions
              </h3>
              <hr className={styles.rulesHr} />
              <br />
              <p className={styles.decorativep2}>
                Messages that are purely for insult or hate purposes will be
                removed but messages that discuss a person&apos;s opinion, or
                argue for a point, may not be removed.
              </p>
              <p className={styles.decorativep2}>
                Here&apos;s an example the moderators provided to illustrate
                that point:
              </p>
              <blockquote className={styles.quoteS}>
                &quot;For example, &apos;all women are whores&apos; is
                unacceptable, but &apos;women who marry men only for money are
                whores&apos; is acceptable&quot;
              </blockquote>
            </div>
          </div>
        </div>
        <div className={styles.spacing}>
          <div className={styles.personalCard}>
            <h4 className={styles.title}>Personal Note:</h4>
            <hr className={styles.prLine} />
            <br />
            <p>The quote is hilarious. That&apos;s all I have to say.</p>
            <br />
          </div>
        </div>
        <div className={styles.spacing2}>
          <div className={styles.multipleC}>
            <div className={styles.accentcardW2}>
              <h3 className={styles.title_center}>
                Researchers Must Contact Moderators
              </h3>
              <hr className={styles.rulesHr2} />
              <br />
              <p className={styles.decorativep3}>
                Researchers need to contact the moderators of the subreddit
                before posting and asking for information.
              </p>
              <p className={styles.decorativep3}>
                This is done to prevent the sub from being misrepresented or
                surveys from being flooded with false responses.
              </p>
            </div>
            <div className={styles.middle}></div>
            <div className={styles.accentcardW2}>
              <h3 className={styles.title_center}>
                Gender Reversal Posts Requirements
              </h3>
              <hr className={styles.rulesHr2} />
              <br />
              <p className={styles.decorativep3}>
                All posts speculating what would happen if the gender roles were
                reversed must use comparable examples.
              </p>
              <p className={styles.decorativep3}>
                Those that do not meet these requirements will be removed
              </p>
            </div>
          </div>
        </div>
        <div className={styles.spacing}>
          <div className={styles.personalCard}>
            <h4 className={styles.title}>Personal Note:</h4>
            <hr className={styles.prLine} />
            <br />
            <p>
              Since I was not conducting any surveys, I did not believe it was
              necessary for me to contact the moderators and state that I&apos;m
              a researcher.
            </p>
            <br />
          </div>
        </div>
        <div className={styles.spacing2}>
          <div className={styles.multipleC}>
            <div className={styles.accentcardR2}>
              <h3 className={styles.title_center}>Miscellaneous Rule</h3>
              <hr className={styles.rulesHr} />
              <br />
              <p className={styles.decorativep2}>
                <strong>Direct Quote From the Moderators:</strong>
              </p>
              <p className={styles.decorativep2}>
                &quot;Mods may use their discretion to resolve any situation not
                explicitly covered here. In addition, young accounts (low karma
                and/or low age) will not be given any benefit of the doubt and
                may be permanently banned at any point for seemingly minor
                infractions. This is to cut down on trolls, etc.&quot;
              </p>
            </div>
            <div className={styles.middle}></div>
            <div className={styles.accentcardR2}>
              <h3 className={styles.title_center}>
                Titles Must Be Descriptive
              </h3>
              <hr className={styles.rulesHr} />
              <br />
              <p className={styles.decorativep2}>
                Users should know what they are clicking on based on the title
                of a post and users searching for a topic should be easily able
                to find it. Make sure to explain your topic thoroughly but do
                not go overboard. Also, try to avoid typos, ambiguities, and
                redundant words.
              </p>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
